###
GET http://127.0.0.1:3004/tasks/task/68508cf34a01cbccdbf2f245

###
POST http://127.0.0.1:3004/tasks/task
Content-Type: application/json

{
  "task": {
    "title": "Avanzar con el Trabajo para Anderson",
    "description": "Realizar la 1º parte",
    "date": "2025-06-17",
    "assignedTo": "684f627f00cef237d803146b"
  }
}




###
DELETE http://127.0.0.1:3004/tasks/task/6850906a8d0e08406ad5eb5a

###
PUT http://127.0.0.1:3004/tasks/task/685090d1e3f80be157fa7784
Content-Type: application/json

{
    "title": "TEST DE UPDATE 5",
    "description": "Estamos testeando el Update para ver que onda"
}